spring:
  application:
    name: userinfo-server
  profiles:
    active: userinfoB
server:
  port: 8002
eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true